<?php

include_once('wc_config.php');

$dave = array();
$dave['name'] = 'Davinder';
$dave['A']['ARGENTINA'] = ARGENTINA;
$dave['B']['GERMANY'] = GERMANY;
$dave['C']['BELGIUM'] = BELGIUM;
$dave['D']['ITALY'] = ITALY;
$dave['E']['COLOMBIA'] = COLOMBIA;
$dave['F']['IVORY COAST'] = IVORY;
$dave['G']['ECUADOR'] = ECUADOR;
$dave['H']['BOSNIA'] = BOSNIA;
$dave['I']['SOUTH KOREA'] = KOREA;
$dave['J']['COSTA RICA'] = COSTA;
$dave['K']['MESSI'] = MESSI;
$dave['L']['LUKAKU'] = LUKAKU;
$dave['M']['VAN PERSIE'] = PERSIE;
$dave['N']['BENZEMA'] = BENZEMA;
$dave['O']['BALOTELLI'] = BALOTELLI;
$dave['P']['MULLER'] = MULLER;
$dave['Q']['PEDRO'] = PEDRO;
$dave['R']['DZEKO'] = DZEKO;
$dave['S']['PIRLO'] = PIRLO;
$dave['T']['IMMOBILE'] = IMMOBILE;
$dave['U']['KERZHAKOV'] = KERZHAKOV;
$dave['V']['GYAN'] = GYAN;
define('DAVE', serialize($dave));

$dave2 = array();
$dave2['name'] = 'Fridge';
$dave2['A']['ARGENTINA'] = ARGENTINA;
$dave2['B']['GERMANY'] = GERMANY;
$dave2['C']['FRANCE'] = FRANCE;
$dave2['D']['HOLLAND'] = HOLLAND;
$dave2['E']['SWITZERLAND'] = SWITZ;
$dave2['F']['ENGLAND'] = ENGLAND;
$dave2['G']['MEXICO'] = MEXICO;
$dave2['H']['GHANA'] = GHANA;
$dave2['I']['GREECE'] = GREECE;
$dave2['J']['IRAN'] = IRAN;
$dave2['K']['MESSI'] = MESSI;
$dave2['L']['AGUERO'] = AGUERO;
$dave2['M']['VAN PERSIE'] = PERSIE;
$dave2['N']['BENZEMA'] = BENZEMA;
$dave2['O']['ROBBEN'] = ROBBEN;
$dave2['P']['GIROUD'] = GIROUD;
$dave2['Q']['ROONEY'] = ROONEY;
$dave2['R']['DROGBA'] = DROGBA;
$dave2['S']['HAZARD'] = HAZARD;
$dave2['T']['STURRIDGE'] = STURRIDGE;
$dave2['U']['HERNANDEZ'] = HERNANDEZ;
$dave2['V']['GYAN'] = GYAN;
define('DAVE2', serialize($dave2));

$aviva = array();
$aviva['name'] = 'Mrs. Spicy Ricey';
$aviva['A']['BRAZIL'] = BRAZIL;
$aviva['B']['SPAIN'] = SPAIN;
$aviva['C']['BELGIUM'] = BELGIUM;
$aviva['D']['ITALY'] = ITALY;
$aviva['E']['COLOMBIA'] = COLOMBIA;
$aviva['F']['CHILE'] = CHILE;
$aviva['G']['ECUADOR'] = ECUADOR;
$aviva['H']['USA'] = USA;
$aviva['I']['SOUTH KOREA'] = KOREA;
$aviva['J']['COSTA RICA'] = COSTA;
$aviva['K']['NEYMAR'] = NEYMAR;
$aviva['L']['SUAREZ'] = SUAREZ;
$aviva['M']['DIEGO COSTA'] = DCOSTA;
$aviva['N']['HULK'] = HULK;
$aviva['O']['NEGREDO'] = NEGREDO;
$aviva['P']['TORRES'] = TORRES;
$aviva['Q']['DAVID VILLA'] = VILLA;
$aviva['R']['DROGBA'] = DROGBA;
$aviva['S']['FORLAN'] = FORLAN;
$aviva['T']['DEMPSEY'] = DEMPSEY;
$aviva['U']['JACKSON MARTINEZ'] = MARTINEZ;
$aviva['V']['GYAN'] = GYAN;
define('AVIVA', serialize($aviva));

$seb = array();
$seb['name'] = 'The Double Ent-Andres';
$seb['A']['BRAZIL'] = BRAZIL;
$seb['B']['SPAIN'] = SPAIN;
$seb['C']['BELGIUM'] = BELGIUM;
$seb['D']['PORTUGAL'] = PORTUGAL;
$seb['E']['COLOMBIA'] = COLOMBIA;
$seb['F']['URUGUAY'] = URUGUAY;
$seb['G']['MEXICO'] = MEXICO;
$seb['H']['GREECE'] = GREECE;
$seb['I']['ALGERIA'] = ALGERIA;
$seb['J']['COSTA RICA'] = COSTA;
$seb['K']['MESSI'] = MESSI;
$seb['L']['RONALDO'] = RONALDO;
$seb['M']['HIGUAIN'] = HIGUAIN;
$seb['N']['FRED'] = FRED;
$seb['O']['NEGREDO'] = NEGREDO;
$seb['P']['MULLER'] = MULLER;
$seb['Q']['KLOSE'] = KLOSE;
$seb['R']['HUNTELAAR'] = HUNTELAAR;
$seb['S']['FORLAN'] = FORLAN;
$seb['T']['POSTIGA'] = POSTIGA;
$seb['U']['JACKSON MARTINEZ'] = MARTINEZ;
$seb['V']['MITROGLOU'] = MITROGLOU;
define('SEB', serialize($seb));

$tenley = array();
$tenley['name'] = 'Tenley "Messi" Pants';
$tenley['A']['BRAZIL'] = BRAZIL;
$tenley['B']['GERMANY'] = GERMANY;
$tenley['C']['FRANCE'] = FRANCE;
$tenley['D']['PORTUGAL'] = PORTUGAL;
$tenley['E']['COLOMBIA'] = COLOMBIA;
$tenley['F']['CHILE'] = CHILE;
$tenley['G']['ECUADOR'] = ECUADOR;
$tenley['H']['GREECE'] = GREECE;
$tenley['I']['NIGERIA'] = NIGERIA;
$tenley['J']['COSTA RICA'] = COSTA;
$tenley['K']['NEYMAR'] = NEYMAR;
$tenley['L']['LUKAKU'] = LUKAKU;
$tenley['M']['DIEGO COSTA'] = DCOSTA;
$tenley['N']['BENZEMA'] = BENZEMA;
$tenley['O']['OSCAR'] = OSCAR;
$tenley['P']['MULLER'] = MULLER;
$tenley['Q']['PEDRO'] = PEDRO;
$tenley['R']['DZEKO'] = DZEKO;
$tenley['S']['HAZARD'] = HAZARD;
$tenley['T']['STURRIDGE'] = STURRIDGE;
$tenley['U']['DRMIC'] = DRMIC;
$tenley['V']['EMENIKE'] = EMENIKE;
define('TENLEY', serialize($tenley));

$ryan = array();
$ryan['name'] = "Coley's Copa Do Mundo Equipe";
$ryan['A']['ARGENTINA'] = ARGENTINA;
$ryan['B']['GERMANY'] = GERMANY;
$ryan['C']['BELGIUM'] = BELGIUM;
$ryan['D']['ITALY'] = ITALY;
$ryan['E']['COLOMBIA'] = COLOMBIA;
$ryan['F']['URUGUAY'] = URUGUAY;
$ryan['G']['ECUADOR'] = ECUADOR;
$ryan['H']['GHANA'] = GHANA;
$ryan['I']['NIGERIA'] = NIGERIA;
$ryan['J']['HONDURAS'] = HONDURAS;
$ryan['K']['MESSI'] = MESSI;
$ryan['L']['AGUERO'] = AGUERO;
$ryan['M']['DIEGO COSTA'] = DCOSTA;
$ryan['N']['FRED'] = FRED;
$ryan['O']['BALOTELLI'] = BALOTELLI;
$ryan['P']['MULLER'] = MULLER;
$ryan['Q']['KLOSE'] = KLOSE;
$ryan['R']['DZEKO'] = DZEKO;
$ryan['S']['HAZARD'] = HAZARD;
$ryan['T']['STURRIDGE'] = STURRIDGE;
$ryan['U']['JACKSON MARTINEZ'] = MARTINEZ;
$ryan['V']['GYAN'] = GYAN;
define('RYAN', serialize($ryan));

$christa = array();
$christa['name'] = 'Victorious Secret';
$christa['A']['BRAZIL'] = BRAZIL;
$christa['B']['SPAIN'] = SPAIN;
$christa['C']['BELGIUM'] = BELGIUM;
$christa['D']['PORTUGAL'] = PORTUGAL;
$christa['E']['RUSSIA'] = RUSSIA;
$christa['F']['URUGUAY'] = URUGUAY;
$christa['G']['CROATIA'] = CROATIA;
$christa['H']['GHANA'] = GHANA;
$christa['I']['NIGERIA'] = NIGERIA;
$christa['J']['AUSTRALIA'] = AUSTRALIA;
$christa['K']['MESSI'] = MESSI;
$christa['L']['SUAREZ'] = SUAREZ;
$christa['M']['HIGUAIN'] = HIGUAIN;
$christa['N']['HULK'] = HULK;
$christa['O']['NEGREDO'] = NEGREDO;
$christa['P']['MULLER'] = MULLER;
$christa['Q']['ROONEY'] = ROONEY;
$christa['R']['DZEKO'] = DZEKO;
$christa['S']['PIRLO'] = PIRLO;
$christa['T']['POSTIGA'] = POSTIGA;
$christa['U']['KERZHAKOV'] = KERZHAKOV;
$christa['V']['GYAN'] = GYAN;
define('CHRISTA', serialize($christa));

$char = array();
$char['name'] = 'My Chinese Roomate Won a Pool';
$char['A']['BRAZIL'] = BRAZIL;
$char['B']['GERMANY'] = GERMANY;
$char['C']['FRANCE'] = FRANCE;
$char['D']['ITALY'] = ITALY;
$char['E']['RUSSIA'] = RUSSIA;
$char['F']['ENGLAND'] = ENGLAND;
$char['G']['MEXICO'] = MEXICO;
$char['H']['USA'] = USA;
$char['I']['NIGERIA'] = NIGERIA;
$char['J']['AUSTRALIA'] = AUSTRALIA;
$char['K']['NEYMAR'] = NEYMAR;
$char['L']['AGUERO'] = AGUERO;
$char['M']['VAN PERSIE'] = PERSIE;
$char['N']['BENZEMA'] = BENZEMA;
$char['O']['BALOTELLI'] = BALOTELLI;
$char['P']['MULLER'] = MULLER;
$char['Q']['KLOSE'] = KLOSE;
$char['R']['HUNTELAAR'] = HUNTELAAR;
$char['S']['PIRLO'] = PIRLO;
$char['T']['DEMPSEY'] = DEMPSEY;
$char['U']['KERZHAKOV'] = KERZHAKOV;
$char['V']['EMENIKE'] = EMENIKE;
define('CHAR', serialize($char));



$mike = array();
$mike['name'] = 'Azzurri';
$mike['A']['ARGENTINA'] = ARGENTINA;
$mike['B']['GERMANY'] = GERMANY;
$mike['C']['FRANCE'] = FRANCE;
$mike['D']['ITALY'] = ITALY;
$mike['E']['SWITZERLAND'] = SWITZ;
$mike['F']['UR A GAY'] = URUGUAY;
$mike['G']['MEXICO'] = MEXICO;
$mike['H']['USA'] = USA;
$mike['I']['NIGERIA'] = NIGERIA;
$mike['J']['COSTA RICA'] = COSTA;
$mike['K']['MESSI'] = MESSI;
$mike['L']['SUAREZ'] = SUAREZ;
$mike['M']['HIGUAIN'] = HIGUAIN;
$mike['N']['FRED'] = FRED;
$mike['O']['BALOTELLI'] = BALOTELLI;
$mike['P']['MULLER'] = MULLER;
$mike['Q']['DAVID VILLA'] = VILLA;
$mike['R']['DZEKO'] = DZEKO;
$mike['S']['HAZARD'] = HAZARD;
$mike['T']['DEMPSEY'] = DEMPSEY;
$mike['U']['HERNANDEZ'] = HERNANDEZ;
$mike['V']['EMENIKE'] = EMENIKE;
define('MIKE', serialize($mike));


$james = array();
$james['name'] = 'Immobile';
$james['A']['BRAZIL'] = BRAZIL;
$james['B']['SPAIN'] = SPAIN;
$james['C']['BELGIUM'] = BELGIUM;
$james['D']['PORTUAL'] = PORTUAL;
$james['E']['COLOMBIA'] = COLOMBIA;
$james['F']['URUGUAY'] = URUGUAY;
$james['G']['CROATIA'] = CROATIA;
$james['H']['BOSNIA'] = BOSNIA;
$james['I']['NIGERIA'] = NIGERIA;
$james['J']['COSTA RICA'] = COSTA;
$james['K']['NEYMAR'] = NEYMAR;
$james['L']['RONALDO'] = RONALDO;
$james['M']['DIEGO COSTA'] = DCOSTA;
$james['N']['FRED'] = FRED;
$james['O']['BALOTELLI'] = BALOTELLI;
$james['P']['TORRES'] = TORRES;
$james['Q']['PEDRO'] = PEDRO;
$james['R']['DZEKO'] = DZEKO;
$james['S']['HAZARD'] = HAZARD;
$james['T']['STURRIDGE'] = STURRIDGE;
$james['U']['JACKSON MARTINEZ'] = MARTINEZ;
$james['V']['EMENIKE'] = EMENIKE;
define('JAMES', serialize($james));

$brynn = array();
$brynn['name'] = 'ReadySetGoooooo';
$brynn['A']['ARGENTINA'] = ARGENTINA;
$brynn['B']['GERMANY'] = GERMANY;
$brynn['C']['BELGIUM'] = BELGIUM;
$brynn['D']['ITALY'] = ITALY;
$brynn['E']['SWITZERLAND'] = SWITZ;
$brynn['F']['URUGUAY'] = URUGUAY;
$brynn['G']['CROATIA'] = CROATIA;
$brynn['H']['BOSNIA'] = V;
$brynn['I']['NIGERIA'] = NIGERIA;
$brynn['J']['AUSTRALIA'] = AUSTRALIA;
$brynn['K']['MESSI'] = MESSI;
$brynn['L']['AGUERO'] = AGUERO;
$brynn['M']['HIGUAIN'] = HIGUAIN;
$brynn['N']['FRED'] = FRED;
$brynn['O']['BALOTELLI'] = BALOTELLI;
$brynn['P']['MULLER'] = MULLER;
$brynn['Q']['KLOSE'] = KLOSE;
$brynn['R']['DZEKO'] = DZEKO;
$brynn['S']['HAZARD'] = HAZARD;
$brynn['T']['IMMOBILE'] = IMMOBILE;
$brynn['U']['KERZHAKOV'] = KERZHAKOV;
$brynn['V']['MITROGLOU'] = MITROGLOU;
define('BRYNN', serialize($brynn));

$clara = array();
$clara['name'] = 'Golden Poop Winner 2014';
$clara['A']['BRAZIL'] = BRAZIL;
$clara['B']['SPAIN'] = SPAIN;
$clara['C']['BELGIUM'] = BELGIUM;
$clara['D']['PORTUGAL'] = PORTUGAL;
$clara['E']['SWITZERLAND'] = SWITZ;
$clara['F']['URUGUAY'] = URUGUAY;
$clara['G']['MEXICO'] = MEXICO;
$clara['H']['GREECE'] = GREECE;
$clara['I']['NIGERIA'] = NIGERIA;
$clara['J']['IRAN'] = IRAN;
$clara['K']['MESSI'] = MESSI;
$clara['L']['RONALDO'] = RONALDO;
$clara['M']['VAN PERSIE'] = PERSIE;
$clara['N']['FRED'] = FRED;
$clara['O']['ROBBEN'] = ROBBEN;
$clara['P']['MULLER'] = MULLER;
$clara['Q']['ROONEY'] = ROONEY;
$clara['R']['HUNTELAAR'] = HUNTELAAR;
$clara['S']['FORLAN'] = FORLAN;
$clara['T']['POSTIGA'] = POSTIGA;
$clara['U']['DRMIC'] = DRMIC;
$clara['V']['MITROGLOU'] = MITROGLOU;
define('CLARA', serialize($clara));


/********************************/

$wc_teams = array();
$wc_teams[] = $dave;
$wc_teams[] = $dave2;
$wc_teams[] = $aviva;
$wc_teams[] = $seb;
$wc_teams[] = $tenley;
$wc_teams[] = $ryan;
$wc_teams[] = $christa;
$wc_teams[] = $char;
$wc_teams[] = $mike;
$wc_teams[] = $james;
$wc_teams[] = $brynn;
$wc_teams[] = $clara;
define('WC_TEAMS', serialize($wc_teams));

?>