<?php

include_once('wc_config.php');

$dave = array();
$dave['name'] = 'Zidane\'s Forehead';
$dave['A']['GERMANY'] = GERMANY;
$dave['B']['ITALY'] = ITALY;
$dave['C']['FRANCE_C'] = FRANCE_C;
$dave['D']['CROATIA'] = CROATIA;
$dave['E']['AUSTRIA'] = AUSTRIA;
$dave['F']['TURKEY'] = TURKEY;
$dave['G']['SLOVAKIA'] = SLOVAKIA;
$dave['H']['MBAPPE'] = MBAPPE;
$dave['I']['RONALDO'] = RONALDO;
$dave['J']['IMMOBILE'] = IMMOBILE;
$dave['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$dave['L']['WERNER'] = WERNER;
$dave['M']['BELOTTI'] = BELOTTI;
$dave['N']['YILMAZ'] = YILMAZ;
$dave['O']['ERIKSON'] = ERIKSON;
$dave['P']['SEFEROVIC'] = SEFEROVIC;
define('DAVE', serialize($dave));

$dave2 = array();
$dave2['name'] = 'Materazzi\'s Chest';
$dave2['A']['FRANCE'] = FRANCE;
$dave2['B']['PORTUGAL'] = PORTUGAL;
$dave2['C']['BELGIUM_C'] = BELGIUM_C;
$dave2['D']['DENMARK'] = DENMARK;
$dave2['E']['CZECH'] = CZECH;
$dave2['F']['SWEDEN'] = SWEDEN;
$dave2['G']['SLOVAKIA'] = SLOVAKIA;
$dave2['H']['LUKAKU'] = LUKAKU;
$dave2['I']['RONALDO'] = RONALDO;
$dave2['J']['GNABRY'] = GNABRY;
$dave2['K']['HAZARD'] = HAZARD;
$dave2['L']['RASHFORD'] = RASHFORD;
$dave2['M']['BALE'] = BALE;
$dave2['N']['YARMOLENKO'] = YARMOLENKO;
$dave2['O']['DZUBA'] = DZUBA;
$dave2['P']['ADAMS'] = ADAMS;
define('DAVE2', serialize($dave2));

$mike = array();
$mike['name'] = 'I Wanna Pukki';
$mike['A']['FRANCE'] = FRANCE;
$mike['B']['SPAIN'] = SPAIN;
$mike['C']['BELGIUM_C'] = BELGIUM_C;
$mike['D']['DENMARK'] = DENMARK;
$mike['E']['POLAND'] = POLAND;
$mike['F']['TURKEY'] = TURKEY;
$mike['G']['SLOVAKIA'] = SLOVAKIA;
$mike['H']['MBAPPE'] = MBAPPE;
$mike['I']['RONALDO'] = RONALDO;
$mike['J']['MORATA'] = MORATA;
$mike['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$mike['L']['WERNER'] = WERNER;
$mike['M']['BELOTTI'] = BELOTTI;
$mike['N']['YILMAZ'] = YILMAZ;
$mike['O']['ERIKSON'] = ERIKSON;
$mike['P']['PUKKI'] = PUKKI;
define('MIKE', serialize($mike));

$mike2 = array();
$mike2['name'] = 'Vinny Bellisimos';
$mike2['A']['BELGIUM'] = BELGIUM;
$mike2['B']['SPAIN'] = SPAIN;
$mike2['C']['ITALY_C'] = ITALY_C;
$mike2['D']['CROATIA'] = CROATIA;
$mike2['E']['CZECH'] = CZECH;
$mike2['F']['SWITZERLAND'] = SWITZERLAND;
$mike2['G']['FINLAND'] = FINLAND;
$mike2['H']['LUKAKU'] = LUKAKU;
$mike2['I']['RONALDO'] = RONALDO;
$mike2['J']['IMMOBILE'] = IMMOBILE;
$mike2['K']['HAZARD'] = HAZARD;
$mike2['L']['RASHFORD'] = RASHFORD;
$mike2['M']['BELOTTI'] = BELOTTI;
$mike2['N']['SCHICK'] = SCHICK;
$mike2['O']['QUAISON'] = QUAISON;
$mike2['P']['SEFEROVIC'] = SEFEROVIC;
define('MIKE2', serialize($mike2));

$crime = array();
$crime['name'] = 'Touch Me Softly';
$crime['A']['GERMANY'] = GERMANY;
$crime['B']['ITALY'] = ITALY;
$crime['C']['FRANCE_C'] = FRANCE_C;
$crime['D']['CROATIA'] = CROATIA;
$crime['E']['RUSSIA'] = RUSSIA;
$crime['F']['TURKEY'] = TURKEY;
$crime['G']['SLOVAKIA'] = SLOVAKIA;
$crime['H']['MBAPPE'] = MBAPPE;
$crime['I']['GRIEZMANN'] = GRIEZMANN;
$crime['J']['GNABRY'] = GNABRY;
$crime['K']['HAZARD'] = HAZARD;
$crime['L']['WERNER'] = WERNER;
$crime['M']['BELOTTI'] = BELOTTI;
$crime['N']['YILMAZ'] = YILMAZ;
$crime['O']['DZUBA'] = DZUBA;
$crime['P']['PUKKI'] = PUKKI;
define('CRIME', serialize($crime));

$crime2 = array();
$crime2['name'] = 'Go Habs Go';
$crime2['A']['GERMANY'] = GERMANY;
$crime2['B']['HOLLAND'] = HOLLAND;
$crime2['C']['FRANCE_C'] = FRANCE_C;
$crime2['D']['DENMARK'] = DENMARK;
$crime2['E']['CZECH'] = CZECH;
$crime2['F']['TURKEY'] = TURKEY;
$crime2['G']['SCOTLAND'] = SCOTLAND;
$crime2['H']['MBAPPE'] = MBAPPE;
$crime2['I']['GRIEZMANN'] = GRIEZMANN;
$crime2['J']['GNABRY'] = GNABRY;
$crime2['K']['STERLING'] = STERLING;
$crime2['L']['WERNER'] = WERNER;
$crime2['M']['BALE'] = BALE;
$crime2['N']['SCHICK'] = SCHICK;
$crime2['O']['ERIKSON'] = ERIKSON;
$crime2['P']['ADAMS'] = ADAMS;
define('CRIME2', serialize($crime2));

$corey = array();
$corey['name'] = 'Curious Jorginho';
$corey['A']['FRANCE'] = FRANCE;
$corey['B']['ITALY'] = ITALY;
$corey['C']['ENGLAND_C'] = ENGLAND_C;
$corey['D']['DENMARK'] = DENMARK;
$corey['E']['RUSSIA'] = RUSSIA;
$corey['F']['TURKEY'] = TURKEY;
$corey['G']['SLOVAKIA'] = SLOVAKIA;
$corey['H']['KANE'] = KANE;
$corey['I']['GRIEZMANN'] = GRIEZMANN;
$corey['J']['IMMOBILE'] = IMMOBILE;
$corey['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$corey['L']['RASHFORD'] = RASHFORD;
$corey['M']['FERNANDES'] = FERNANDES;
$corey['N']['YILMAZ'] = YILMAZ;
$corey['O']['ERIKSON'] = ERIKSON;
$corey['P']['PUKKI'] = PUKKI;
define('COREY', serialize($corey));

$corey2 = array();
$corey2['name'] = 'Blaise Everyday';
$corey2['A']['FRANCE'] = FRANCE;
$corey2['B']['ITALY'] = ITALY;
$corey2['C']['BELGIUM_C'] = BELGIUM_C;
$corey2['D']['DENMARK'] = DENMARK;
$corey2['E']['CZECH'] = CZECH;
$corey2['F']['SWITZERLAND'] = SWITZERLAND;
$corey2['G']['SLOVAKIA'] = SLOVAKIA;
$corey2['H']['LUKAKU'] = LUKAKU;
$corey2['I']['RONALDO'] = RONALDO;
$corey2['J']['GNABRY'] = GNABRY;
$corey2['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$corey2['L']['WERNER'] = WERNER;
$corey2['M']['BELOTTI'] = BELOTTI;
$corey2['N']['YILMAZ'] = YILMAZ;
$corey2['O']['DZUBA'] = DZUBA;
$corey2['P']['SEFEROVIC'] = SEFEROVIC;
define('COREY2', serialize($corey2));

$james = array();
$james['name'] = 'Hungary Turkey';
$james['A']['FRANCE'] = FRANCE;
$james['B']['SPAIN'] = SPAIN;
$james['C']['ITALY_C'] = ITALY_C;
$james['D']['CROATIA'] = CROATIA;
$james['E']['POLAND'] = POLAND;
$james['F']['TURKEY'] = TURKEY;
$james['G']['SCOTLAND'] = SCOTLAND;
$james['H']['MBAPPE'] = MBAPPE;
$james['I']['DEPAY'] = DEPAY;
$james['J']['IMMOBILE'] = IMMOBILE;
$james['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$james['L']['TORRES'] = TORRES;
$james['M']['FERNANDES'] = FERNANDES;
$james['N']['YILMAZ'] = YILMAZ;
$james['O']['ERIKSON'] = ERIKSON;
$james['P']['ADAMS'] = ADAMS;
define('JAMES', serialize($james));

$james2 = array();
$james2['name'] = 'Pukki Hazard';
$james2['A']['ENGLAND'] = ENGLAND;
$james2['B']['PORTUGAL'] = PORTUGAL;
$james2['C']['BELGIUM_C'] = BELGIUM_C;
$james2['D']['DENMARK'] = DENMARK;
$james2['E']['POLAND'] = POLAND;
$james2['F']['TURKEY'] = TURKEY;
$james2['G']['SCOTLAND'] = SCOTLAND;
$james2['H']['KANE'] = KANE;
$james2['I']['RONALDO'] = RONALDO;
$james2['J']['IMMOBILE'] = IMMOBILE;
$james2['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$james2['L']['TORRES'] = TORRES;
$james2['M']['FERNANDES'] = FERNANDES;
$james2['N']['YILMAZ'] = YILMAZ;
$james2['O']['ERIKSON'] = ERIKSON;
$james2['P']['PUKKI'] = PUKKI;
define('JAMES2', serialize($james2));

$ryan = array();
$ryan['name'] = 'Coley\'s Euro Cup Team A';
$ryan['A']['ENGLAND'] = ENGLAND;
$ryan['B']['ITALY'] = ITALY;
$ryan['C']['FRANCE_C'] = FRANCE_C;
$ryan['D']['CROATIA'] = CROATIA;
$ryan['E']['POLAND'] = POLAND;
$ryan['F']['SWITZERLAND'] = SWITZERLAND;
$ryan['G']['SCOTLAND'] = SCOTLAND;
$ryan['H']['KANE'] = KANE;
$ryan['I']['GRIEZMANN'] = GRIEZMANN;
$ryan['J']['IMMOBILE'] = IMMOBILE;
$ryan['K']['LEWANDOWSKI'] = LEWANDOWSKI;
$ryan['L']['RASHFORD'] = RASHFORD;
$ryan['M']['BELOTTI'] = BELOTTI;
$ryan['N']['YILMAZ'] = YILMAZ;
$ryan['O']['ERIKSON'] = ERIKSON;
$ryan['P']['ADAMS'] = ADAMS;
define('RYAN', serialize($ryan));

$ryan2 = array();
$ryan2['name'] = 'Coley\'s Euro Cup Team B';
$ryan2['A']['ENGLAND'] = ENGLAND;
$ryan2['B']['HOLLAND'] = HOLLAND;
$ryan2['C']['FRANCE_C'] = FRANCE_C;
$ryan2['D']['DENMARK'] = DENMARK;
$ryan2['E']['POLAND'] = POLAND;
$ryan2['F']['TURKEY'] = TURKEY;
$ryan2['G']['SLOVAKIA'] = SLOVAKIA;
$ryan2['H']['KANE'] = KANE;
$ryan2['I']['GRIEZMANN'] = GRIEZMANN;
$ryan2['J']['IMMOBILE'] = IMMOBILE;
$ryan2['K']['STERLING'] = STERLING;
$ryan2['L']['TORRES'] = TORRES;
$ryan2['M']['FERNANDES'] = FERNANDES;
$ryan2['N']['YARMOLENKO'] = YARMOLENKO;
$ryan2['O']['ERIKSON'] = ERIKSON;
$ryan2['P']['SEFEROVIC'] = SEFEROVIC;
define('RYAN2', serialize($ryan2));

/********************************/

$wc_teams = array();
$wc_teams[] = $dave;
$wc_teams[] = $dave2;
$wc_teams[] = $mike;
$wc_teams[] = $mike2;
$wc_teams[] = $crime;
$wc_teams[] = $crime2	;
$wc_teams[] = $corey;
$wc_teams[] = $corey2;
$wc_teams[] = $ryan;
$wc_teams[] = $ryan2;
$wc_teams[] = $james;
$wc_teams[] = $james2;
define('WC_TEAMS', serialize($wc_teams));
